### ISSUE TITLE
Error when launched from Dockge on raspberry 3

### ISSUE THREAD

**Issue by abda11ah** [kgregor98/grass#1]
Hello,

I've just run the command on Dockge (portainer equivalent) and as far as I can see it can't find the image.

My raspberry is a raspberry 3B 1GB RAM (arm64).

```
[+] Running 0/1
 ⠸ grass Pulling                                                                                    1.3s 
choosing an image from manifest list docker://camislav/grass:latest: no image found in image index for architecture arm64, variant "v8", OS linux
```

**Comment by abda11ah** [comment]
oops solved,

i just added **:debian** into my compose.yaml file at the line **image: camislav/grass:debian**

(My current raspberry OS is dietpi)

**Comment by kgregor98** [comment]
That's right, I haven't have the time to create a workaround that lets me keep the image Alpine-based and with WebDriverManager yet. The Debian image should work on ARM based devices, like the RPI. 
I will keep you updated once I have a working solution.

**Comment by kgregor98** [comment]
New update pushed to both repo and Docker Hub. Try redownloading the image, it should now support ARMv7 / ARM64 out of the box on the :latest tag
