### ISSUE TITLE
Proposal: create automation for new nodepay project

### ISSUE THREAD

**Issue by doubleTroub1e** [kgregor98/grass#21]
Hey, your project is really great, I've started it on Raspberry Pi and it is running pretty nice for me.
also, I've found a pretty similar project called nodepay,  here is link to it: https://app.nodepay.ai/register?ref=3iXL7IuXXwKQVE6 (this is my ref code). 
this is pretty much the same, install an extension and keep on earning points, can you please  create same for this project if you're interested in and if you have some time?

**Comment by doubleTroub1e** [comment]
hi again, I've create smth like this
https://github.com/doubleTroub1e/nodepayai

I do believe that it would be very interesting to create single app which can farm grass and nodepay  in same docker image

**Comment by binhnv56** [comment]
Nodepay require capcha for login. Could you please recheck it?

**Comment by rhcit** [comment]
> Nodepay require capcha for login. Could you please recheck it?

Please refer to this https://github.com/Kellphy/Nodepay
