### ISSUE TITLE
Network 0%

### ISSUE THREAD

**Issue by toastyy00** [kgregor98/grass#5]
Sorry, this may not be related, but how can I prevent my network score from 0%, I use a VPS from Contabo. I'm sure this installation was successful because on the web the status is connected but the score is 0% 
![SmartSelect_20240218_161740_Chrome](https://github.com/kgregor98/grass/assets/108380151/9bf88140-1930-4dec-bc9b-b4889643d5c5)
![SmartSelect_20240218_161823_Termius](https://github.com/kgregor98/grass/assets/108380151/740128f9-77ad-4b39-8f2f-3197bad33c90)

**Comment by kgregor98** [comment]
The grass project doesn't allow to run on non-residential IP's. So any VPS'es, or dedicated server/corporate IP's will always result in the score being 0
