### ISSUE TITLE
Installed but says connected "false"

### ISSUE THREAD

**Issue by Friendly11** [kgregor98/grass#8]
[root@crankk-183cc92f ~]# docker logs 940f097726cf
Downloading extension...
Downloaded! Installing extension and driver manager...
Installed! Starting...
Could not start with Manager! Trying to default to manual path...
Started! Logging in...
Logging in...
Logging in...
Logging in...
Logging in...
Logging in...
Logging in...
Logging in...
Logging in...
Logged in! Waiting for connection...
Connected! Starting API...
 * Serving Flask app 'main'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.x.x.x:80
 * Running on http://172.xx.xx.x:80
Press CTRL+C to quit
192.168.1.170 - - [08/Mar/2024 20:11:25] "GET / HTTP/1.1" 200 -
192.168.1.170 - - [08/Mar/2024 20:11:25] "GET /favicon.ico HTTP/1.1" 404 -
[root@crankk-183cc92f ~]#

This is what It says when I connect to the web browser with the port:
{"connected":false,"epoch_earnings":"37,946.67","network_quality":"100"}

**Comment by Rejang-IT-King** [comment]
Don't worry, you still can earn it.
